# NB: this file was automatically generated by Dynare
#     from dynare_model.mod
#
function dynamic_params_derivs(y, x, params, steady_state, it_,ss_param_deriv, ss_param_2nd_deriv)
@inbounds begin
T = zeros(0)
rp = zeros(31, 23);
gp = zeros(31, 39, 23);
end
return (rp, gp)
end
