# NB: this file was automatically generated by Dynare
#     from dynare_model.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(1, 1);
gp = zeros(1, 1, 1);
end
return (rp, gp)
end
