# NB: this file was automatically generated by Dynare
#     from dynare_model.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(31, 23);
gp = zeros(31, 31, 23);
end
return (rp, gp)
end
